// <auto-generated />
using System;
using ClaimFlow.Documents.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClaimFlow.Documents.Persistence.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20261002141358_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaimFlow.Documents.Analysis.ClaimAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DocumentCount")
                        .HasColumnType("integer");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("Refused")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId", "CreatedAt");

                    b.ToTable("claim_analyses", "documents");
                });

            modelBuilder.Entity("ClaimFlow.Documents.Domain.ClaimDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UploadedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId", "UploadedAt");

                    b.ToTable("claim_documents", "documents");
                });

            modelBuilder.Entity("ClaimFlow.Documents.Analysis.ClaimAnalysis", b =>
                {
                    b.OwnsMany("ClaimFlow.Documents.Analysis.AnalysisCitation", "Citations", b1 =>
                        {
                            b1.Property<Guid>("ClaimAnalysisId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("CitedText")
                                .IsRequired();

                            b1.Property<Guid>("DocumentId");

                            b1.Property<string>("DocumentTitle")
                                .IsRequired();

                            b1.Property<int?>("EndPage");

                            b1.Property<int>("Number");

                            b1.Property<int?>("StartPage");

                            b1.HasKey("ClaimAnalysisId", "__synthesizedOrdinal");

                            b1.ToTable("claim_analyses", "documents");

                            b1
                                .ToJson("Citations")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ClaimAnalysisId");
                        });

                    b.Navigation("Citations");
                });
#pragma warning restore 612, 618
        }
    }
}
